### ISSUE TITLE
SnipsConfigParser.write_configuration_file should return True when it succeeds

### ISSUE THREAD

**Issue by koenvervloesem** [snipsco/snips-app-template-py#1]
The helper function `SnipsConfigParser.write_configuration_file` returns `False` when it fails, but doesn't return anything when writing the configuration succeeds. It would be more logical if it returns `True` then.

That would make it cleaner to test if writing succeeded in an app:

```
if SnipsConfigParser.write_configuration_file(CONFIG_INI, self.config):
  # Do something
else:
  # Give an error message or do something else
```
Moreover, the helper function `SnipsConfigParser.read_configuration_file` always returns a value: the dictionary with configuration values if reading succeeds and an empty dictionary when it fails. So it would be more consistent if `SnipsConfigParser.write_configuration_file` does the same.

**Comment by CoorFun** [comment]
Hello:

Thanks for this suggestion. We have already changed. 

https://github.com/snipsco/snips-app-template-py/commit/21158a7f42263379498ef762b2851c66bfa8f50e
