### ISSUE TITLE
Migrate app template to Python 3

### ISSUE THREAD

**Issue by koenvervloesem** [snipsco/snips-app-template-py#3]
Python 2.7 will not be maintained [after January 1, 2020](https://pythonclock.org/). Snips users are already [getting errors](https://forum.snips.ai/t/python-pip-error-in-update-assistant/1494) for every app they install:

```
Error setting up virtualenv, one or more actions might not be able to run. Reason :
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
```

When pip drops support for Python 2.7, Snips apps won’t work anymore with this new version.

Just for fun, I changed `setup.sh` for one of my apps based on this app template to make use of Python 3, and it [seems to work](https://forum.snips.ai/t/snips-python-3-instead-of-python-2/1378/6?u=koan), although I have to test it more thoroughly.

This app template should be updated so app developers will write their apps for Python 3.

**Comment by koenvervloesem** [comment]
I now wrote a [HOWTO for converting Snips skills to Python 3](https://forum.snips.ai/t/howto-convert-your-snips-skills-to-python-3/1511) on the Snips forum, with a suggestion for a new setup.sh. The code changes needed for the app template seem limited.

**Comment by anthonyray** [comment]
Thanks for filing this issue. We are actively working on it and we'll keep you posted when action code written with snippets will support Python 3.

**Comment by metal3d** [comment]
I created a PR #4 if you're interested.

**Comment by flatsiedatsie** [comment]
I use it with Python 3. All I have to do was change the print statements to use brackets, and change the ConfigParser dependency to use lower case. In the end I just removed that parsing, since it was superfluous anyway.

**Comment by CoorFun** [comment]
It's been done by @metal3d
