### ISSUE TITLE
Test for python binary in setup.sh is inappropriate

### ISSUE THREAD

**Issue by franc6** [snipsco/snips-app-template-py#6]
setup.sh contains code to make sure that the python binary exists as a regular file, using "which python2".  This doesn't really make sense.    If which returns any data at all, it will return a file that is executable, and that file could be a symbolic link.  If that happens, then the test will fail (because it's a symbolic link, not a regular file), indicating that python2 cannot be found, when it fact it does exist.  There is no condition whereby "which python2" will return a string for a file that doesn't exist or cannot be executed.

Instead, the check should be a simple existence of the string.  If which doesn't find a program, it'll return an empty string.  A check such as:

PYTHON=`which python2`
if [ -z "$PYTHON" ]

would be adequate, and won't prevent the script from working if python2 happens to be a symbolic link.

**Comment by franc6** [comment]
The fix is incorrect.  The code reads:
```
    if [ -z "$PYTHON" ]
    then
        echo "could not find python3"
    fi
```
It should be:
```
    if [ -z "$PYTHON" ]
        echo "could not find python3"
    fi
```
 
The -z argument to test (or [) returns true if the string is empty.  If $PYTHON is empty, then there's no python3 binary.  I'm sorry it wasn't clear that a check with -z would report there is no python binary, but I had assumed the authors would understand what -z does. :(

**Comment by CoorFun** [comment]
@franc6 

Thanks, you are right. It was my fault.
