### ISSUE TITLE
[setup.sh]  `/usr/bin/env: 'bash -e': No such file or directory`

### ISSUE THREAD

**Issue by iinoxx** [snipsco/snips-app-template-py#8]
I got a lot of Problems while installing my assistant's skills.

When i try to run the setup.sh shell-scripts i get the error: 

`/usr/bin/env: 'bash -e': No such file or directory`

This seems to be a shellscript portability issue with the shebang and the specified `-e` parameter.

We could replace

```bash
#!/usr/bin/env bash -e
```
with

```bash
#!/usr/bin/env bash
set -e
```

**Comment by CoorFun** [comment]
👍 

Done https://github.com/snipsco/snips-app-template-py/commit/4a27eb6bef141daec5b21effb9b9e57ff42d7e5a
